
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Tue Apr 27 21:20:36 CDT 2010
//----------------------------------------------------

package cse431.lab5.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOAT_LIT = 40;
  public static final int CHAR_LIT = 41;
  public static final int OP_NE = 31;
  public static final int CHAR = 4;
  public static final int ASTERISK = 24;
  public static final int EQUALS = 34;
  public static final int SLASH = 23;
  public static final int PLUSOP = 21;
  public static final int OP_GT = 27;
  public static final int MINUSOP = 22;
  public static final int DOUBLE = 5;
  public static final int LPAREN = 8;
  public static final int OP_AND = 32;
  public static final int INT = 3;
  public static final int OP_INC = 19;
  public static final int RPAREN = 9;
  public static final int SEMICOLON = 11;
  public static final int OP_GE = 29;
  public static final int BANG = 25;
  public static final int COMMA = 10;
  public static final int CLASS = 12;
  public static final int IF = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 18;
  public static final int TRUE = 35;
  public static final int error = 1;
  public static final int OP_LT = 26;
  public static final int NULL = 14;
  public static final int OP_OR = 33;
  public static final int VOID = 13;
  public static final int OP_LE = 28;
  public static final int LBRACE = 6;
  public static final int ELSE = 16;
  public static final int WHILE = 17;
  public static final int OP_DEC = 20;
  public static final int RBRACE = 7;
  public static final int OP_EQ = 30;
  public static final int FALSE = 36;
  public static final int STRING_LIT = 39;
  public static final int INT_LIT = 38;
  public static final int IDENTIFIER = 37;
}

